"""Add sections to ClassLevel

Revision ID: fb5c87842a73
Revises: 0008_scope_local
Create Date: 2026-07-08 18:37:39.392439+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5c87842a73'
down_revision: Union[str, None] = '0008_scope_local'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_levels', sa.Column('sections', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_levels', 'sections')
    # ### end Alembic commands ###
